# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LLM_policing_risk',
                'doc_host': 'https://AndreasThinks.github.io',
                'git_url': 'https://github.com/AndreasThinks/LLM_policing_risk',
                'lib_path': 'LLM_policing_risk'},
  'syms': {'LLM_policing_risk.core': {'LLM_policing_risk.core.foo': ('core.html#foo', 'LLM_policing_risk/core.py')}}}
